config/routes.rb
Rails.application.routes.draw do
  get '/foo' => 'pages#foo'
  resources :todos do
    collection do
      # Not based on a specific todo

      # /todos/completed
      get '/completed' => 'todos#completed'
    end

    member do
      # Is based on a specific todo
      # /todos/:id/whatever

      post '/complete' => 'todos#complete'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def foo
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def completed
    @todos = Todo.where(completed: true)
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    Todo.create(todo_params)
    redirect_to todos_path
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.update(completed: true)
    redirect_to todos_path
  end

  private

  def todo_params
    params.require(:todo).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todosapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/foo.html.erb
Hello!

<% (1..10).each do |num| %>
  <%= num %>
<% end %>

app/views/todos/_form.html.erb
<%= form_for todo do |f| %>
  <div>
    <label>Name</label>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Edit "<%= @todo.name %>"</h1>
<%= render 'form', todo: @todo %>

app/views/todos/index.html.erb
<h1>Todos</h1>
<h4><%= link_to "Create a todo", new_todo_path %></h4>

<% @todos.each do |todo| %>
  <h3
    style="<%= todo.completed ? 'text-decoration: line-through;' : nil %>"
  >
    <%= link_to todo.name, todo %>
  </h3>
  <%= button_to 'Complete todo', complete_todo_path(todo) unless todo.completed %>
<% end %>

app/views/todos/new.html.erb
<h1>New todo</h1>
<%= render 'form', todo: @todo %>

app/views/todos/show.html.erb
<h1><%= @todo.name %></h1>
<h2>Complete: <%= @todo.completed %></h2>
<h3>Created <%= @todo.created_at %></h3>
<h3>Updated <%= @todo.updated_at %></h3>

<h4><%= link_to "Edit todo", edit_todo_path(@todo) %></h4>